vault_site/urls.py
"""vault_site URL Configuration"""

from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import (
    include,
    path,
    re_path,
)

from vault import api, views, fixity_api, forms

from vault.rest_api import router as rest_api_router


urlpatterns = [
    path("", views.index, name="index"),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "accounts/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(form_class=forms.VaultPasswordResetForm),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            form_class=forms.VaultSetPasswordForm
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "accounts/logout_then_login",
        auth_views.logout_then_login,
        name="logout_then_login",
    ),
    path("dashboard", views.dashboard, name="dashboard"),
    path("create_collection", views.create_collection, name="create_collection"),
    re_path(
        "^collections/(?P<path>.*)",
        views.render_web_components_file_view,
        name="collections",
    ),
    path("reports/<int:report_id>", views.report, name="report"),
    path("reports/fixity/<int:report_id>", views.fixity_report, name="fixity_report"),
    path("deposit", views.deposit, name="deposit"),
    path("deposit/web", views.deposit_web, name="deposit_web"),
    path("deposit/compat", views.deposit_compat, name="deposit_compat"),
    path("deposit/cli", views.deposit_cli, name="deposit_cli"),
    path("deposit/mail", views.deposit_mail, name="deposit_mail"),
    path("deposit/flow", views.deposit_flow, name="deposit_flow"),
    path("deposit/<int:deposit_id>", views.deposit_report, name="deposit_report"),
    path("deposit/ait", views.deposit_ait, name="deposit_ait"),
    path("administration", views.administration, name="administration"),
    path("administration/plan", views.administration_plan, name="administration_plan"),
    path(
        "administration/users", views.administration_users, name="administration_users"
    ),
    path("administration/help", views.administration_help, name="administration_help"),
    path("api/collections", api.collections, name="api_collections"),
    path("api/reports", api.reports, name="api_reports"),
    path("api/collections_stats", api.collections_stats, name="api_collections_stats"),
    path("api/reports_files", api.reports_files, name="api_reports_files"),
    path(
        "api/collections_summary",
        api.collections_summary,
        name="api_collections_summary",
    ),
    path(
        "api/reports_files/<collection_id>",
        api.reports_files,
        name="api_reports_files_by_collection",
    ),
    path(
        "api/report_summary/<collection_id>/<report_id>",
        api.report_summary,
        name="api_report_summary",
    ),
    path(
        "api/report_files/<collection_id>/<report_id>",
        api.report_files,
        name="api_report_files",
    ),
    path(
        "api/flow_chunk",
        api.flow_chunk,
        name="api_flow_chunk",
    ),
    path("api/get_events/<collection_id>", api.get_events, name="api_get_events"),
    path("api/register_deposit", api.register_deposit, name="api_register_deposit"),
    path("api/deposit_status", api.hashed_status, name="api_deposit_status"),
    path("api/warning_deposit", api.warning_deposit, name="api_warning_deposit"),
    # Include the Django Rest Framework API routes.
    path("api/", include(rest_api_router.urls)),
    re_path(
        r"^fixitter/files/(?P<org_id>\d+)/(?P<path>.*)",
        fixity_api.list_files,
        name="fixitter_files",
    ),
    path(
        "fixitter/shafs/<int:org_id>/<sha256_sum>",
        fixity_api.stream_from_shafs,
        name="fixitter_shafs",
    ),
    path(
        "fixitter/run/<int:org_id>/<collection_name>/<token>",
        fixity_api.run_collection_name,
        name="fixitter_run",
    ),
    path(
        "fixitter/postback/<int:org_id>/<int:collection_id>/<token>",
        fixity_api.postback,
        name="fixitter_postback",
    ),
    path("admin/", admin.site.urls),
]

vault/models.py
# pylint: disable=too-few-public-methods

import logging
import re
import typing

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import FieldError
from django.core.mail import send_mail
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import UniqueConstraint, IntegerChoices, Sum, Count
from django.db.models.functions import Coalesce
from django.dispatch import receiver
from django.db.models.signals import (
    pre_save,
    post_save,
)

from vault.ltree import LtreeField
from vault.pb_utils import (
    InvalidPetaboxPath,
    get_presigned_url,
)

from vault import utils

TEBIBYTE = 2**40
logger = logging.getLogger(__name__)


class TreeNodeException(Exception):
    """Raised when an invalid TreeNode operation is requested"""


class ReplicationFactor(IntegerChoices):
    DEFAULT = 2, "2x"
    THREE = 3, "3x"
    FOUR = 4, "4x"


class FixityFrequency(models.TextChoices):
    DEFAULT = "TWICE_YEARLY", "Twice Yearly"
    QUARTERLY = "QUARTERLY", "Quarterly"
    MONTHLY = "MONTHLY", "Monthly"


class Geolocation(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Plan(models.Model):
    name = models.CharField(max_length=255)
    price_per_terabyte = models.DecimalField(max_digits=10, decimal_places=2)
    default_replication = models.IntegerField(
        choices=ReplicationFactor.choices, default=ReplicationFactor.DEFAULT
    )
    default_geolocations = models.ManyToManyField(Geolocation)
    default_fixity_frequency = models.CharField(
        choices=FixityFrequency.choices, default=FixityFrequency.DEFAULT, max_length=50
    )

    def __str__(self):
        return self.name


class Organization(models.Model):
    name = models.CharField(max_length=255, unique=True)
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT)
    quota_bytes = models.PositiveBigIntegerField(default=TEBIBYTE)
    tree_node = models.ForeignKey(
        "TreeNode", blank=True, null=True, on_delete=models.PROTECT
    )
    pbox_collection = models.CharField(max_length=255, blank=True, null=True)

    def filepath(self):
        org = re.sub(r"[^a-zA-Z0-9_\-\/\.]", "_", self.name)
        return f"/files/{org}/"

    def __str__(self):
        return self.name


class User(AbstractUser):
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.username


class Collection(models.Model):
    name = models.CharField(max_length=255)
    organization = models.ForeignKey(
        Organization, on_delete=models.PROTECT, db_index=False
    )
    target_replication = models.IntegerField(
        choices=ReplicationFactor.choices, default=ReplicationFactor.DEFAULT
    )
    target_geolocations = models.ManyToManyField(Geolocation)
    fixity_frequency = models.CharField(
        choices=FixityFrequency.choices, default=FixityFrequency.DEFAULT, max_length=50
    )
    tree_node = models.ForeignKey(
        "TreeNode", blank=True, null=True, on_delete=models.PROTECT
    )

    def filepath(self):
        collection_name = re.sub(r"[^a-zA-Z0-9_\-\/\.]", "_", self.name)
        return f"{self.organization.filepath()}{collection_name}/"

    def last_fixity_report(self):
        return (
            Report.objects.filter(
                collection__pk=self.pk, report_type=Report.ReportType.FIXITY
            )
            .order_by("-ended_at")
            .first()
        )

    def __str__(self):
        return self.name

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=["organization", "name"], name="vault_collection_org_and_name"
            )
        ]


class DeferredJSONReportManager(models.Manager):
    """Report model manager which defers load of report_json field.

    The report_json can be large (particularly for large collections). There are several
    cases where we load all reports for a Collection or Organization.
    """

    def get_queryset(self):
        return super().get_queryset().defer("report_json")


class Report(models.Model):
    class ReportType(models.TextChoices):
        FIXITY = "FIXITY", "Fixity"
        DEPOSIT = "DEPOSIT", "Deposit"

    collection = models.ForeignKey(Collection, on_delete=models.PROTECT)
    report_type = models.CharField(
        choices=ReportType.choices, max_length=20, default=ReportType.FIXITY
    )
    started_at = models.DateTimeField()
    ended_at = models.DateTimeField()
    total_size = models.PositiveBigIntegerField()
    file_count = models.PositiveBigIntegerField()
    collection_total_size = models.PositiveBigIntegerField()
    collection_file_count = models.PositiveBigIntegerField()
    error_count = models.PositiveBigIntegerField()
    missing_location_count = models.PositiveBigIntegerField()
    mismatch_count = models.PositiveBigIntegerField()
    avg_replication = models.PositiveSmallIntegerField()
    # report_json format see conftest.py:make_fixity_report()
    report_json = models.JSONField(blank=True, null=True)
    report_json_version = models.PositiveSmallIntegerField(blank=True, null=True)

    objects = DeferredJSONReportManager()

    def __str__(self):
        return f"{self.report_type}-{self.collection.pk}-{self.started_at}"


md5_validator = RegexValidator(
    r"^[a-zA-Z0-9]{32}$", "only hex-encoded md5 hashes are allowed"
)
sha1_validator = RegexValidator(
    r"^[a-zA-Z0-9]{40}$", "only hex-encoded sha1 hashes are allowed"
)
sha256_validator = RegexValidator(
    r"^[a-zA-Z0-9]{64}$", "only hex-encoded sha256 hashes are allowed"
)


class File(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.PROTECT)
    client_filename = models.TextField()
    staging_filename = models.TextField()
    md5_sum = models.CharField(
        max_length=32, validators=[md5_validator], blank=True, null=True
    )
    sha1_sum = models.CharField(
        max_length=40, validators=[sha1_validator], blank=True, null=True
    )
    sha256_sum = models.CharField(max_length=64, validators=[sha256_validator])
    size = models.PositiveBigIntegerField()
    file_type = models.CharField(max_length=255, blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deletion_date = models.DateTimeField(blank=True, null=True)
    uploaded_by = models.ForeignKey(
        User, on_delete=models.PROTECT, blank=True, null=True
    )
    comment = models.TextField(blank=True, null=True)

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=[
                    "collection",
                    "client_filename",
                    "staging_filename",
                    "sha256_sum",
                ],
                name="unique_file",
            )
        ]

    def __str__(self):
        return self.client_filename


class Deposit(models.Model):
    class State(models.TextChoices):
        REGISTERED = "REGISTERED", "Registered"
        UPLOADED = "UPLOADED", "Uploaded"
        HASHED = "HASHED", "Hashed"
        REPLICATED = "REPLICATED", "Replicated"
        COMPLETE_WITH_ERRORS = "COMPLETE_WITH_ERRORS", "Complete With Errors"

    organization = models.ForeignKey(Organization, on_delete=models.PROTECT)
    collection = models.ForeignKey(Collection, on_delete=models.PROTECT)
    #: TreeNode which is the root into which this Deposit is being made.
    #: Referenced TreeNode must be either type COLLECTION or FOLDER
    parent_node = models.ForeignKey("TreeNode", on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    state = models.CharField(
        choices=State.choices, default=State.REGISTERED, max_length=50
    )

    registered_at = models.DateTimeField(auto_now_add=True)
    uploaded_at = models.DateTimeField(blank=True, null=True)
    hashed_at = models.DateTimeField(blank=True, null=True)
    replicated_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        reg_dt = self.registered_at.strftime("%Y-%m-%d %H:%M:%S")
        return f"Deposit-{self.organization_id}-{self.collection_id}-{reg_dt}"

    def make_deposit_report(self):
        deposit_stats = TreeNode.objects.filter(depositfile__deposit=self).aggregate(
            total_size=Coalesce(Sum("size"), 0), file_count=Coalesce(Count("*"), 0)
        )
        collection_root = self.collection.tree_node
        collection_stats = TreeNode.objects.filter(
            path__descendant=collection_root.path
        ).aggregate(
            collection_total_size=Coalesce(Sum("size"), 0),
            collection_file_count=Coalesce(Count("*"), 0),
        )
        report = Report(
            collection=self.collection,
            report_type=Report.ReportType.DEPOSIT,
            started_at=self.registered_at,
            ended_at=self.hashed_at,  # TODO: should this be replicated_at?
            total_size=deposit_stats["total_size"],
            file_count=deposit_stats["file_count"],
            collection_total_size=collection_stats["collection_total_size"],
            collection_file_count=collection_stats["collection_file_count"],
            error_count=0,
            missing_location_count=0,
            mismatch_count=0,
            avg_replication=self.collection.target_replication,
        )
        report.save()
        self.send_deposit_report_email()

    def send_deposit_report_email(self):
        deposit_report_link = f"https://{settings.CURRENT_HOST}/vault/deposit/{self.id}"
        collections_link = f"https://{settings.CURRENT_HOST}/vault/collections"
        message = f"""
Hello {self.user.username}

Your deposit to {self.collection.name} is now complete:
View deposit report {deposit_report_link}
View all collections {collections_link}

templates/vault/administration.html
{% extends "vault/base.html" %}
{% block header_title %}Administration{% endblock header_title %}
{% block sticky_message %}{% endblock sticky_message %}
{% block subnav %}
  <div class="row subnav">
    <div class="small-12 columns">
      <div class="row">
        <div class="subnav-box columns">
          <div class="left subnav-link collections {% if active_subnav == 'plan' %}active{% endif %}">
            <a class="" href="{{ url('administration_plan') }}">Current Plan</a>
          </div>
          <div class="left subnav-link collections {% if active_subnav == 'users' %}active{% endif %}">
            <a class="" href="{{ url('administration_users') }}">Users</a>
          </div>
          <div class="left subnav-link collections {% if active_subnav == 'help' %}active{% endif %}">
            <a class="" href="{{ url('administration_help') }}">Help Center</a>
          </div>
          <hr>
        </div>
      </div>
    </div>
  </div>
{% endblock subnav %}

templates/vault/administration_help.html
{% extends "vault/administration.html" %} {% set active_subnav = "help" %} {%
set breadcrumbs = (("Vault", "dashboard"), ("Administration", "administration"),
("Help Center", "administration/help")) %} {% block content %}
  <div class="row">
    <div class="large-12 columns">
      <h2>Help Center</h2>
      <div class="panel">
        <p>
          We are here to support you. If you have questions or challenges during
          this pilot period please contact the Product Team at vault@archive.org.
        </p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/vault/collection.html
{% extends "vault/base.html" %}
{% set breadcrumbs = (("Vault", "dashboard"), ("Collections", "collections"), (collection.name, "collections/"+ collection_id)) %}
{% block header_title %}{{ collection.name }}{% endblock header_title %}
{% block sticky_message %}{% endblock sticky_message %}
{% block subnav %}{% endblock subnav %}
{% block content %}
  <div class="row">
    <div class="large-8 columns">
      <br>
      <br>
      <h2>Collection Stats</h2>
      <ul>
        <li>Total Size: {% if collection_stats.total_size is none %}-{% else %}{{ collection_stats.total_size|filesizeformat(binary=True) }}{% endif %}</li>
        <li>File Count: {{ collection_stats.file_count if collection_stats.file_count is gt 0 else "-" }}</li>
        <li>Last Modified: {% if collection_stats.last_modified is none %}-{% else %}{{ collection_stats.last_modified.strftime('%B %-d, %Y') }}{% endif %}</li>
      </ul>

      {% if collection_stats.file_count is gt 0 %}
        <a href="{{ url("files", args=[collection.name]) }}" target="_blank" class="button padding-top padding-bottom half">View Files</a>
      {% endif %}

      <h2>Collection Events</h2>
      {% if events %}
        {% set headers = ("Event Type", "Started", "Completed", "Total Size", "File Count", "Error Count", "View Details") %}
        <table class="small-12 columns">
          <thead>
            {% for header in headers %}
              <th>{{ header }}</th>
            {% endfor %}
            <tr></tr>
          </thead>
          {% for event in events %}
            {%  if "Deposit" in event.__class__.__name__ %}
              <tbody>
                <tr>
                  <td>{% if 15 <= event.id <= 96 %}Migration{% else %}Deposit{% endif %}</td>
                  <td>{{ event.registered_at.strftime('%B %-d, %Y') }}</td>
                  <td>{% if event.hashed_at %}{{ event.hashed_at.strftime('%B %-d, %Y') }}{% else %}-{% endif %}</td>
                  <td>{{ event.total_size|filesizeformat(binary=True) }}</td>
                  <td>{{ event.file_count }}</td>
                  <td>{{ event.error_count }}</td>
                  <td><a href="{{ url('deposit_report', args=(event.pk,)) }}">View Details</a></td>
                </tr>
              </tbody>
            {% else %}
              <tbody>
                <tr>
                  <td>{{ event.get_report_type_display() }}</td>
                  <td>{{ event.started_at.strftime('%B %-d, %Y') }}</td>
                  <td>{{ event.ended_at.strftime('%B %-d, %Y') }}</td>
                  <td>{{ event.total_size|filesizeformat(binary=True) }}</td>
                  <td>{{ event.file_count }}</td>
                  <td>{{ event.error_count }}</td>
                  <td><a href="{{ url('report', args=(event.pk,)) }}">View Details</a></td>
                </tr>
              </tbody>
            {% endif %}
          {% endfor %}
        </table>
      {% else %}
        <p>No events yet.</p>
      {% endif %}
    </div>
    <div class="large-4 columns">
      <br>
      <br>
      <h2>Collection Settings</h2>
      <div class="panel">
        <form action="{{ url("collection", args=(collection.pk,)) }}" method="post">
          {{ csrf_input }}
          {{ form }}
          <input type="submit" value="Edit Settings", class="button small padding-top padding-bottom half">
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/vault/collections.html
{% extends "vault/base.html" %}
{% set breadcrumbs = (("Vault", "dashboard"), ("Collections", "collections")) %}
{% block header_title %}Collections{% endblock header_title %}
{% block sticky_message %}{% endblock sticky_message %}
{% block subnav %}{% endblock subnav %}
{% block content %}
  <div class="row">
    <div class="small-12 columns">
      <br>
      <br>
      {% if collections %}
        <div class="panel">
          <form action="{{ url("collections") }}" method="post">
            {{ csrf_input }}
            {{ form }}
            <input type="submit" value="Create Collection" class="button small padding-top padding-bottom half" style="margin:0">
          </form>
        </div>
        {% set headers = ("Collection Name", "Total Size", "File Count", "Last Modified", "Most Recent Fixity Report", "View Files", "Edit Settings") %}
        <table class="small-12 columns">
          <thead>
            {% for header in headers %}
              <th>{{ header }}</th>
            {% endfor %}
            <tr></tr>
          </thead>
          {% for collection in collections %}
            <tbody>
              <tr>
                <td><a href="{{ url("collection", args=(collection.collection_id,)) }}">{{ collection.name }}</a></td>
                {% if collection.total_size is none %}
                  <td>-</td>
                {% else %}
                  <td>{{ collection.total_size|filesizeformat(binary=true) }}</td>
                {% endif %}
                <td>{{ collection.file_count }}</td>
                {% if collection.last_modified is none %}
                  <td>-</td>
                {% else %}
                  <td>{{ collection.last_modified.strftime('%B %-d, %Y') }}</td>
                {% endif %}
                {% if collection.last_fixity_report is none %}
                  <td>-</td>
                {% else %}
                  <td>{{ collection.last_fixity_report().ended_at.strftime('%B %-d, %Y') }}</td>
                {% endif %}
                <td>{% if collection.file_count is gt 0 %}<a href="{{ url("files", args=[collection.name]) }}" target="_blank">View Files</a>{% else %} - {% endif %}</td>
                <td><a href="{{ url("collection", args=(collection.collection_id,)) }}">Edit Settings</a></td>
              </tr>
            </tbody>
          {% endfor %}
        </table>
      {% else %}
        <h3>Create your first collection</h3>
        <form action="{{ url("collections") }}" method="post">
          {{ csrf_input }}
          {{ form }}
          <input type="submit" value="Create Collection" class="button small padding-top padding-bottom half left">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock content %}

templates/vault/deposit.html
{% extends "vault/base.html" %}

{% block head_deposit %}
  <script src="/vault/static/js/preserve-directory-info.js"></script>
  <script src="/vault/static/js/ext/spark-md5/spark-md5.js"></script>
  <script src="/vault/static/js/ext/chunkfile/chunkfile.js"></script>
{% endblock head_deposit %}

{% block header_title %}Deposit{% endblock header_title %}
{% block sticky_message %}{% endblock sticky_message %}
{% block subnav %}
  <div class="row subnav">
    <div class="small-12 columns">
      <div class="row">
        <div class="subnav-box columns">
          <!-- <div class="left subnav-link collections {% if active_subnav == 'web' %}active{% endif %}">
					<a class="" href="{{ url('deposit_web') }}">Web Uploader</a>
				</div> -->
          <div class="left subnav-link collections {% if active_subnav == 'test' %}active{% endif %}">
            <a class="" href="{{ url('deposit_flow') }}">Web Uploader</a>
          </div>
          <div class="left subnav-link collections {% if active_subnav == 'cli' %}active{% endif %}">
            <a class="" href="{{ url('deposit_cli') }}">Command Line</a>
          </div>
          <div class="left subnav-link collections {% if active_subnav == 'mail' %}active{% endif %}">
            <a class="" href="{{ url('deposit_mail') }}">Mail Drive</a>
          </div>
          {#				<div class="left subnav-link collections {% if active_subnav == 'debug' %}active{% endif %}">#}
          {#                    			<a class="" href="{{ url('deposit_debug') }}">Debug META</a>#}
          {#                		</div>#}

          <div class="left subnav-link collections {% if active_subnav == 'ait' %}active{% endif %}">
            <a class="" href="{{ url('deposit_ait') }}">Import IA Collection</a>
          </div>
          <hr>
        </div>
      </div>
    </div>
  </div>
{% endblock subnav %}

templates/vault/deposit_ait.html
{% extends "vault/deposit.html" %} {% set active_subnav = "ait" %} {% set
breadcrumbs = (("Vault", "dashboard"), ("Deposit", "deposit"), ("Import IA
Collection", "deposit/ait")) %} {% block content %}
  <div class="row">
    <div class="large-12 columns">
      <h2>How to Import Your Internet Archive Collections</h2>
      <p>Coming Soon</p>
    </div>
  </div>
{% endblock content %}

templates/vault/deposit_debug.html
{% extends "vault/deposit.html" %}
{% set active_subnav = "debug" %}
{% set breadcrumbs = (("Vault", "dashboard"), ("Deposit", "deposit"), ("Debug META", "deposit_debug")) %}
{% block content %}
  {% if request.user.is_superuser %}
    <pre>
{#{{request.META|pprint}}#}
        </pre>
  {% else %}
    <h2>Unauthorized</h2>
  {% endif %}
{% endblock content %}

templates/vault/files_view.html
{% extends "vault/base.html" %}

{% block sticky_message %}{% endblock sticky_message %}
{% block subnav %}{% endblock subnav %}

{% block header %}

  <header>

    <div class="row" style="font-size: 0.6875rem; color: #888;">
      <div class="small-12 columns" >
        <template id="collection-breadcrumbs" >
          <style>

            .breadcrumbs_list {
              display: inline;
              color: #888;
              margin-top: 18px;
              margin-right: 10px;
              margin-left: 10px;
              list-style: none;

            }
            .breadcrumbs_list a{
              color: #888;
              font-size: 0.6875rem;
              text-decoration: none;
            }
            .breadcrumbs_list:hover{
              text-decoration: underline;
            }
          </style>
          <div><slot name="my-text" ></slot></div>
        </template>
        <collection-breadcrumbs data-path = '{{ path | tojson }}' >
          <ul slot="my-text" style="font-size: 0.6875rem;" id="elements_list">
          </ul>
        </collection-breadcrumbs>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns" style="height: 55px;">
        <div class="bottom medium-8" style="height: 60px;">
          <h1>
            {% block header_title %}All Files{% endblock header_title %}
          </h1>
        </div>
      </div>
    </div>
  </header>

{% endblock header %}

{% block content %}

  <style>
    table {
      margin-top: 4rem;
      margin-bottom: -5rem;
    }
    table thead tr th,
    table thead tr td {
      padding: 0 0.7rem 0rem 0.7rem;
    }
  </style>

  <div class="row" >
    <div class="small-12 columns">
      <div id="first_element"></div>

      <table>
        <thead>
          <th>Name</th>
          <th>Date Modified</th>
          <th>Size</th>
          <th>Type</th>
        </thead>
        <tbody>
          {% if path != "" %}
            <td>
              <a
                class="notepad"
                href="{{ url("files", args=['/'.join(path[:-1].split('/')[:-1])[1:]]) }}"
              >Back</a
                >
              </td>
          {% endif %}
          {% for item in items %}
            <tr>
              {% if item.node_type == "COLLECTION" or item.node_type == "FOLDER"
              %}
              <td class="item_name" id="{{item.id}}">

                <a
                  class="notepad"
                  href="{{ url("files", args=[path[1:] + '/' + item.name if path else item.name]) }}"
                >
                  {{item.name}}
                </a>
              </td>
          {% else %}
            <td>{{item.name.split("/")[-1] }}</td>
          {% endif %}
          <td>{% if item.pre_deposit_modified_at is none %}{% if item.modified_at is none %}-{% else %}{{ item.modified_at.strftime('%Y-%m-%d') }}{% endif %}{% else %}{{item.pre_deposit_modified_at.strftime('%Y-%m-%d')}}{% endif %}</td>
          <td>{% if item.size is none %}-{% else %}{{item.size|filesizeformat(binary=True) }}{% endif %}</td>
          <td>{{ item.node_type|title }}</td>
        </tr>
{% endfor %}
</tbody>
</table>
</div>
</div>

<script src="/vault/static/js/components/files_breadcrumbs.js"></script>

{% endblock content %}